version: '2.1'

volumes:
  db-data:
  redis:

services:
  app:
    container_name: joatu-app
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/joatu
    volumes_from:
      - bundler
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    links:
      - db
    env_file:
      - './docker/.env.app.conf'
    stdin_open: true
    tty: true
  
  db:
    container_name: joatu-db
    volumes:
      - db-data:/var/lib/postgresql/data
    image: mdillon/postgis:latest
    ports:
      - 5432:5432
    env_file:
      - './docker/.env.app.conf'
  
  bundler:
    image: busybox
    volumes:
      - /bundler

  redis:
    image: 'redis:5.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/joatu'
    env_file:
      - './docker/.env.app.conf'

  # cable:
  #   depends_on:
  #     - 'redis'
  #   build: .
  #   command: puma -p 28080 cable/config.ru
  #   ports:
  #     - '28080:28080'
  #   volumes:
  #     - '.:/joatu'
  #   env_file:
  #     - './docker/.env.app.conf'